# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c98d5bfa95b10a7ac42f4e4d3c2f3d5d"
name = "PriceSwitch B2B VAT Toggle"
application_url = "https://vat-toggle.onrender.com"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  uri = "https://vat-full-features.gadget.app/api/webhooks/shopify"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [
  "https://vat-toggle.onrender.com/auth/callback"
]

[app_proxy]
url = "/apps/proxy"
subpath = "vat-toggle"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
