import type { ActionFunctionArgs, HeadersFunction, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData, useNavigation } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import { getVatSettings } from "../vat-settings.server";

export async function loader({ request }: LoaderFunctionArgs) { const { session } = await authenticate.admin(request); const { shop, settings } = await getVatSettings(session.shop); return { settings, translations: await db.vatTranslation.findMany({ where: { shopId: shop.id }, orderBy: { locale: "asc" } }) }; }
export async function action({ request }: ActionFunctionArgs) { const { session } = await authenticate.admin(request); const { shop } = await getVatSettings(session.shop); const form = await request.formData(); if (form.get("intent") === "delete") { const item = await db.vatTranslation.findFirst({ where: { id: String(form.get("id")), shopId: shop.id } }); if (item) await db.vatTranslation.delete({ where: { id: item.id } }); } else { const locale = String(form.get("locale") || "").toLowerCase(); if (!locale) return { error: "Enter a Shopify locale such as fr or de." }; await db.vatTranslation.upsert({ where: { shopId_locale: { shopId: shop.id, locale } }, create: { shopId: shop.id, locale, inclusiveLabel: String(form.get("inclusiveLabel")), exclusiveLabel: String(form.get("exclusiveLabel")), popupTitle: String(form.get("popupTitle")), popupMessage: String(form.get("popupMessage")) }, update: { inclusiveLabel: String(form.get("inclusiveLabel")), exclusiveLabel: String(form.get("exclusiveLabel")), popupTitle: String(form.get("popupTitle")), popupMessage: String(form.get("popupMessage")) } }); } return { saved: true }; }
export default function Languages() { const { settings, translations } = useLoaderData<typeof loader>(); const result = useActionData<typeof action>(); const navigation = useNavigation(); return <s-page heading="Languages"><div className="vat-page"><section className="vat-display-heading"><div><span className="vat-eyebrow">STOREFRONT COPY</span><h1>Language-specific labels</h1><p>The base language uses your Price display settings. Add only the locales that need different VAT labels or popup copy.</p></div></section>{result?.error && <s-banner tone="critical">{result.error}</s-banner>}{result?.saved && <s-banner tone="success">Translation saved.</s-banner>}<section className="vat-panel"><Form method="post" className="vat-form-grid"><label>Locale<input name="locale" placeholder="fr" required/></label><label>Inclusive label<input name="inclusiveLabel" defaultValue={settings.inclusiveLabel} required/></label><label>Exclusive label<input name="exclusiveLabel" defaultValue={settings.exclusiveLabel} required/></label><label>Popup heading<input name="popupTitle" defaultValue={settings.popupTitle} required/></label><label className="vat-grid-wide">Popup message<textarea name="popupMessage" rows={3} defaultValue={settings.popupMessage} required/></label><button className="vat-primary" disabled={navigation.state !== "idle"}>Save translation</button></Form></section><section className="vat-panel"><h2>Saved languages</h2>{translations.length === 0 ? <p className="vat-empty">No translations added. The default storefront language is ready to use.</p> : <div className="vat-table">{translations.map((item) => <div key={item.id}><span><strong>{item.locale}</strong><small>{item.inclusiveLabel} / {item.exclusiveLabel}</small></span><Form method="post"><input type="hidden" name="intent" value="delete"/><input type="hidden" name="id" value={item.id}/><button className="vat-text-button">Remove</button></Form></div>)}</div>}</section></div></s-page>; }
export const headers: HeadersFunction = (args) => boundary.headers(args);
