import type { ActionFunctionArgs, HeadersFunction, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData, useNavigation } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import { getVatSettings } from "../vat-settings.server";

export async function loader({ request }: LoaderFunctionArgs) {
  const { session } = await authenticate.admin(request); const { shop, settings } = await getVatSettings(session.shop);
  return { settings, rates: await db.vatMarketRate.findMany({ where: { shopId: shop.id }, orderBy: [{ marketName: "asc" }, { countryCode: "asc" }] }) };
}
export async function action({ request }: ActionFunctionArgs) {
  const { session, admin } = await authenticate.admin(request); const { shop, settings } = await getVatSettings(session.shop); const form = await request.formData(); const intent = String(form.get("intent"));
  if (intent === "delete") { const id = String(form.get("id")); const rate = await db.vatMarketRate.findFirst({ where: { id, shopId: shop.id } }); if (rate) await db.vatMarketRate.delete({ where: { id: rate.id } }); }
  if (intent === "save") { const marketId = String(form.get("marketId") || "manual"); const countryCode = String(form.get("countryCode") || "").toUpperCase(); const rate = Number(form.get("rate")); if (!Number.isFinite(rate) || rate < 0 || rate > 100) return { error: "Use a VAT rate between 0 and 100." }; await db.vatMarketRate.upsert({ where: { shopId_marketId_countryCode: { shopId: shop.id, marketId, countryCode } }, create: { shopId: shop.id, marketId, marketName: String(form.get("marketName") || countryCode || "Custom market"), countryCode, rate }, update: { marketName: String(form.get("marketName") || countryCode || "Custom market"), rate } }); }
  if (intent === "import") { const response = await admin.graphql(`#graphql query PriceSwitchMarkets { markets(first: 250) { nodes { id name } } }`); const json = await response.json(); const markets = json.data?.markets?.nodes ?? []; await Promise.all(markets.map((market: { id: string; name: string }) => db.vatMarketRate.upsert({ where: { shopId_marketId_countryCode: { shopId: shop.id, marketId: market.id, countryCode: "" } }, create: { shopId: shop.id, marketId: market.id, marketName: market.name, countryCode: "", rate: settings.defaultVatRate }, update: { marketName: market.name } }))); }
  return { saved: true };
}
export default function VatRates() { const { settings, rates } = useLoaderData<typeof loader>(); const result = useActionData<typeof action>(); const navigation = useNavigation(); return <s-page heading="VAT rates"><div className="vat-page"><section className="vat-display-heading"><div><span className="vat-eyebrow">SHOPIFY MARKETS</span><h1>Rates by market</h1><p>Use your default rate as a fallback, then add a rate for each market or country where prices differ.</p></div><Form method="post"><input type="hidden" name="intent" value="import"/><button className="vat-secondary" disabled={navigation.state !== "idle"}>Import Shopify Markets</button></Form></section>{result?.error && <s-banner tone="critical">{result.error}</s-banner>}{result?.saved && <s-banner tone="success">VAT rates saved.</s-banner>}<section className="vat-panel"><div className="vat-panel-heading"><div><h2>Default rate</h2><p>Currently {settings.defaultVatRate}%. Configure it on Price display.</p></div></div><Form method="post" className="vat-inline-form"><input type="hidden" name="intent" value="save"/><label>Market name<input name="marketName" required placeholder="United Kingdom"/></label><label>Country code (optional)<input name="countryCode" maxLength={2} placeholder="GB"/></label><label>VAT rate (%)<input name="rate" type="number" min="0" max="100" step="0.01" required defaultValue={settings.defaultVatRate}/></label><button className="vat-primary" disabled={navigation.state !== "idle"}>Add rate</button></Form></section><section className="vat-panel"><h2>Configured rates</h2>{rates.length === 0 ? <p className="vat-empty">No market overrides yet. Your default VAT rate applies everywhere.</p> : <div className="vat-table">{rates.map((rate) => <div key={rate.id}><span><strong>{rate.marketName}</strong>{rate.countryCode && <small>{rate.countryCode}</small>}</span><b>{rate.rate}%</b><Form method="post"><input type="hidden" name="intent" value="delete"/><input type="hidden" name="id" value={rate.id}/><button className="vat-text-button">Remove</button></Form></div>)}</div>}</section></div></s-page>; }
export const headers: HeadersFunction = (args) => boundary.headers(args);
