import type { ActionFunctionArgs, HeadersFunction, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData, useNavigation } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import { getVatSettings, saveVatSettings, settingsFromForm, syncSettingsToAppMetafield } from "../vat-settings.server";

export const loader = async ({ request }: LoaderFunctionArgs) => { const { session } = await authenticate.admin(request); return getVatSettings(session.shop); };
export const action = async ({ request }: ActionFunctionArgs) => { const { session, admin } = await authenticate.admin(request); const settings = await saveVatSettings(session.shop, settingsFromForm(await request.formData())); await syncSettingsToAppMetafield(admin, settings); return { saved: true }; };

export default function B2BSettings() { const { settings } = useLoaderData<typeof loader>(); const result = useActionData<typeof action>(); const navigation = useNavigation(); return <s-page heading="B2B customers"><div className="vat-settings-layout"><Form method="post" className="vat-card vat-form"><h2>Trade customer rules</h2>{result?.saved && <p className="vat-success">Saved and synced to your theme.</p>}<input type="hidden" name="enableB2BModePresent" value="true" /><label className="vat-check"><input name="enableB2BMode" type="checkbox" defaultChecked={settings.enableB2BMode} /> Automatically recognise trade customers</label><p className="vat-help">A logged-in customer with one of these Shopify tags sees your selected trade price view by default.</p><label>Trade customer tags<input name="b2bCustomerTags" defaultValue={settings.b2bCustomerTags} /><small>Separate tags with commas, for example: wholesale, trade, b2b</small></label><label>Trade customer display<select name="b2bDefaultMode" defaultValue={settings.b2bDefaultMode}><option value="exclusive">Exclusive of VAT</option><option value="inclusive">Inclusive of VAT</option></select></label><button className="vat-primary" type="submit" disabled={navigation.state !== "idle"}>Save B2B settings</button></Form><aside className="vat-card"><span>HOW IT WORKS</span><h2>Simple B2B setup</h2><ol className="vat-steps"><li>Add a tag such as <code>trade</code> to approved customers in Shopify.</li><li>Turn on automatic recognition above.</li><li>Trade customers see your chosen price view after they log in.</li></ol><p className="vat-help">VAT-number applications and approval workflow will be added here next.</p></aside></div></s-page>; }
export const headers: HeadersFunction = (headersArgs) => boundary.headers(headersArgs);
